name: CI
on:
  pull_request:
  push:
    branches:
      - "main"
jobs:
  test:
    name: Small tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: make check-generate
      - run: make test
  e2e:
    name: End-to-End Tests
    runs-on: ubuntu-22.04
    # TODO: add test matrix for kubernetes version
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
        cache: true
    - run: make setup
      working-directory: e2e
    - run: make start
      working-directory: e2e
    - run: make test
      working-directory: e2e
  dry-run:
    name: Dry-run release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup golang
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Setup tag for goreleaser
        run: |
          echo "GORELEASER_CURRENT_TAG=$(git describe --tags --abbrev=0 --match "v*" || echo v0.0.0)" >> $GITHUB_ENV
      - name: GoReleaser
        uses: 'goreleaser/goreleaser-action@v5'
        with:
          distribution: goreleaser
          version: v1.26.2
          args: --snapshot --skip-publish --rm-dist
