name: CI
on:
  pull_request:
  push:
    branches:
      - "main"
jobs:
  test:
    name: Small tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - run: make test
