name: CI
on:
  pull_request:
  push:
    branches:
    - 'main'
env:
  go-version: "1.20"
jobs:
  test:
    name: Small tests
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ env.go-version }}
    - run: make test
