name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  image:
    name: Push Container Image
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build images
        run: |
          docker build -t cat-gate:dev .
      - name: Login to ghcr.io
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${GITHUB_ACTOR} --password-stdin
      - name: Push images
        run: |
          TAG=${GITHUB_REF#refs/tags/v}
          docker tag cat-gate:dev ghcr.io/cybozu-go/cat-gate:${TAG}
          docker push ghcr.io/cybozu-go/cat-gate:${TAG}
  release:
    name: Release on GitHub
    needs: image
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - name: GoReleaser
        uses: 'goreleaser/goreleaser-action@336e29918d653399e599bfca99fadc1d7ffbc9f7'
        with:
          distribution: goreleaser
          version: v1.18.2
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
